### ISSUE TITLE
NPE When attempting to load a scenario

### ISSUE THREAD

**Issue by repligator** [jonathanabennett/megastrike#13]
**Describe the bug**
An NPE is thrown when attempting to load a scenario. The forces and units associated with that scenario do not appear in the lobby.

**To Reproduce**
Press Load Scenario
Select a Scenario

**Expected behavior**
The lobby to be populated by the forces and units associated with that scenario.

**Screenshots**
`Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "s" is null
        at clojure.string$trim.invokeStatic(string.clj:239)
        at clojure.string$trim.invoke(string.clj:235)
        at megastrike.utils$keyword_maker.invokeStatic(utils.clj:43)
        at megastrike.utils$keyword_maker.invoke(utils.clj:37)
        at megastrike.scenario$configure_unit.invokeStatic(scenario.clj:60)
        at megastrike.scenario$configure_unit.invoke(scenario.clj:46)
        at megastrike.scenario$parse_line.invokeStatic(scenario.clj:85)
        at megastrike.scenario$parse_line.invoke(scenario.clj:72)
        at megastrike.scenario$parse_scenario_file.invokeStatic(scenario.clj:141)
        at megastrike.scenario$parse_scenario_file.invoke(scenario.clj:135)
        at megastrike.scenario$setup_scenario.invokeStatic(scenario.clj:146)
        at megastrike.scenario$setup_scenario.invoke(scenario.clj:144)
        at megastrike.gui.lobby.events$fn__3182.invokeStatic(events.clj:34)
        at megastrike.gui.lobby.events$fn__3182.invoke(events.clj:27)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at cljfx.event_handler$wrap_co_effects$fn__2379.invoke(event_handler.clj:10)
        at cljfx.event_handler$wrap_effects$dispatch_sync_BANG___2392.invoke(event_handler.clj:27)
        at cljfx.event_handler$wrap_effects$dispatch_sync_BANG___2392.invoke(event_handler.clj:25)
        at cljfx.lifecycle$make_handler_fn$fn__2051.invoke(lifecycle.clj:131)
        at cljfx.coerce$event_handler$reify__1657.handle(coerce.clj:135)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8923)
        at javafx.scene.control.Button.fire(Button.java:203)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3894)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1887)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2620)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
        at java.base/java.lang.Thread.run(Thread.java:840)
`

**Desktop (please complete the following information):**
Linux
Java 17

**Comment by jonathanabennett** [comment]
Can you tell me which scenario you've tried it on?

**Comment by jonathanabennett** [comment]
@repligator This should be fixed in 122b438. But I am going to use this issue to track other issues with scenarios (full crashes and bad loads). 

I will make a 0.2.1 release shortly which incorporates the fix after I've documented all the longer term issues and fixed any quick fixes I can find.

**Comment by jonathanabennett** [comment]
- [ ] 1st Somerset Strikers - 5 Battle in the Swamp: Sloth Battle Armor loaded as a Sloth Battlemech
- [ ] 1st Somerset Strikers - 8 Liberation of SMA: Infantry and Elementals not loading correctly
- [ ] 1st Somerset Strikers - 9 Malthus Attacks: Infantry does not load correctly
- [ ] Broken Arrow: Board not loading correctly. Damage not applied
- [ ] Down on our Level: Possible type in board name (RiverAmbush vs. River Ambush) Report to Upstream first. and no images are loading.
- [ ] Fist and Dragon: Multiple units not loading on Kurita side.
- [ ] Lucho - All Scenarios: Map names in scenarios do not match (all are missing the sizes).
- [ ] On the Prowl: Path separators go the wrong direction in the scenario (\ instead of /).
- [ ] Great Refusal - Smoke Jaguars: Elementals do not load
- [ ] Great Refusal - Hells Horses: Gnome Battle Armor does not load

The rest of the scenarios were able to load correctly after a few minor changes which will be the next release.

**Comment by jonathanabennett** [comment]
Original bug fixed in v0.2.1

**Comment by repligator** [comment]
Scenarios now load correctly (at least for me).

**Comment by jonathanabennett** [comment]
Fixed in 0.3.0, which should be ready for release

**Comment by jonathanabennett** [comment]
All scenarios working as of latest commit on dev. Will be rolled into the next release.

There are still issues around correct squad size detection, but these will be resolved with the conventional forces release.
