### ISSUE TITLE
NPE When deploying unit that is not part of a scenario

### ISSUE THREAD

**Issue by repligator** [jonathanabennett/megastrike#15]
An NPE is thrown when attempting to deploy a unit.

**To Reproduce**
Add two forces.
Add one unit to each force.
Select a map.
Launch game.
Skip the init phase.
Click the first unit to deploy.
Click a hex.
The unit will not appear, and an NPE is thrown.

**Expected behavior**
The unit deploying in the clicked hex.

**Screenshots**
`java.lang.NullPointerException: Cannot invoke "clojure.lang.IFn.invoke(Object)"
        at megastrike.gui.common$draw_sprite.invokeStatic(common.clj:37)
        at megastrike.gui.common$draw_sprite.invoke(common.clj:18)
        at cljfx.lifecycle$call_context_fn.invokeStatic(lifecycle.clj:473)
        at cljfx.lifecycle$call_context_fn.invoke(lifecycle.clj:472)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$apply.invoke(core.clj:662)
        at cljfx.context$calc_cache_entry.invokeStatic(context.clj:84)
        at cljfx.context$calc_cache_entry.invoke(context.clj:80)
        at cljfx.context$sub_ctx.invokeStatic(context.clj:113)
        at cljfx.context$sub_ctx.doInvoke(context.clj:106)
        at clojure.lang.RestFn.invoke(RestFn.java:442)
        at cljfx.lifecycle$sub_context_fn.invokeStatic(lifecycle.clj:477)
        at cljfx.lifecycle$sub_context_fn.invoke(lifecycle.clj:475)
        at cljfx.lifecycle$fn__2248.invokeStatic(lifecycle.clj:483)
        at cljfx.lifecycle$fn__2248.invoke(lifecycle.clj:482)
        at cljfx.lifecycle$fn__1962$G__1932__1971.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:35)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:32)
        at cljfx.lifecycle$reify__2008.create(lifecycle.clj:42)
        at cljfx.lifecycle$wrap_many$fn__2098$fn__2102$fn__2103.invoke(lifecycle.clj:283)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$wrap_many$fn__2098$fn__2102.invoke(lifecycle.clj:282)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6885)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.lifecycle$wrap_many$fn__2098.invoke(lifecycle.clj:281)
        at cljfx.lifecycle$fn__1962$G__1932__1971.invoke(lifecycle.clj:17)
        at cljfx.composite$create_props$fn__157.invoke(composite.clj:22)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:429)
        at clojure.core$fn__8525.invokeStatic(core.clj:6908)
        at clojure.core$fn__8525.invoke(core.clj:6888)
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6919)
        at clojure.core$reduce_kv.invoke(core.clj:6910)
        at cljfx.composite$create_props.invokeStatic(composite.clj:17)
        at cljfx.composite$create_props.invoke(composite.clj:16)
        at cljfx.composite$create_composite_component.invokeStatic(composite.clj:29)
        at cljfx.composite$create_composite_component.invoke(composite.clj:26)
        at cljfx.lifecycle$fn__1962$G__1932__1971.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:35)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:32)
        at cljfx.lifecycle$reify__2008.create(lifecycle.clj:42)
        at cljfx.lifecycle$fn__2248.invokeStatic(lifecycle.clj:483)
        at cljfx.lifecycle$fn__2248.invoke(lifecycle.clj:482)
        at cljfx.lifecycle$fn__1962$G__1932__1971.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$create_dynamic_component.invokeStatic(lifecycle.clj:35)
        at cljfx.lifecycle$create_dynamic_component.invoke(lifecycle.clj:32)
        at cljfx.lifecycle$reify__2008.create(lifecycle.clj:42)
        at cljfx.lifecycle$wrap_many$fn__2109$fn__2113.invoke(lifecycle.clj:313)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.lifecycle$wrap_many$fn__2109.invoke(lifecycle.clj:296)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.composite$advance_composite_component$fn__181$fn__184.invoke(composite.clj:64)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.composite$advance_composite_component$fn__181.invoke(composite.clj:55)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:48)
        at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$reify__2008$fn__2009.invoke(lifecycle.clj:48)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$reify__2008.advance(lifecycle.clj:48)
        at cljfx.composite$advance_composite_component$fn__181$fn__184.invoke(composite.clj:64)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.composite$advance_composite_component$fn__181.invoke(composite.clj:55)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:48)
        at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$reify__2008$fn__2009.invoke(lifecycle.clj:48)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$reify__2008.advance(lifecycle.clj:48)
        at cljfx.lifecycle$fn__2250.invokeStatic(lifecycle.clj:485)
        at cljfx.lifecycle$fn__2250.invoke(lifecycle.clj:484)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$reify__2008$fn__2009.invoke(lifecycle.clj:48)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$reify__2008.advance(lifecycle.clj:48)
        at cljfx.lifecycle$wrap_extra_props$fn__2160.invoke(lifecycle.clj:372)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$wrap_many$fn__2109$fn__2113.invoke(lifecycle.clj:302)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.lifecycle$wrap_many$fn__2109.invoke(lifecycle.clj:296)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.composite$advance_composite_component$fn__181$fn__184.invoke(composite.clj:64)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.composite$advance_composite_component$fn__181.invoke(composite.clj:55)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:48)
        at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$reify__2008$fn__2009.invoke(lifecycle.clj:48)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$reify__2008.advance(lifecycle.clj:48)
        at cljfx.composite$advance_composite_component$fn__181$fn__184.invoke(composite.clj:64)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6886)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.composite$advance_composite_component$fn__181.invoke(composite.clj:55)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:48)
        at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$reify__2008$fn__2009.invoke(lifecycle.clj:48)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$reify__2008.advance(lifecycle.clj:48)
        at cljfx.composite$advance_composite_component$fn__181$fn__184.invoke(composite.clj:64)
        at clojure.lang.ArraySeq.reduce(ArraySeq.java:119)
        at clojure.core$reduce.invokeStatic(core.clj:6885)
        at clojure.core$reduce.invoke(core.clj:6868)
        at cljfx.composite$advance_composite_component$fn__181.invoke(composite.clj:55)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.composite$advance_composite_component.invokeStatic(composite.clj:48)
        at cljfx.composite$advance_composite_component.invoke(composite.clj:43)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$wrap_on_delete$fn__2221.invoke(lifecycle.clj:441)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$reify__2008$fn__2009.invoke(lifecycle.clj:48)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$reify__2008.advance(lifecycle.clj:48)
        at cljfx.lifecycle$fn__2250.invokeStatic(lifecycle.clj:485)
        at cljfx.lifecycle$fn__2250.invoke(lifecycle.clj:484)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$reify__2008$fn__2009.invoke(lifecycle.clj:48)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$reify__2008.advance(lifecycle.clj:48)
        at cljfx.lifecycle$fn__2014.invokeStatic(lifecycle.clj:64)
        at cljfx.lifecycle$fn__2014.invoke(lifecycle.clj:62)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$wrap_map_desc$fn__2228.invoke(lifecycle.clj:452)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.lifecycle$wrap_context_desc$fn__2239$fn__2240.invoke(lifecycle.clj:467)
        at clojure.core$update.invokeStatic(core.clj:6231)
        at clojure.core$update.invoke(core.clj:6223)
        at cljfx.lifecycle$wrap_context_desc$fn__2239.invoke(lifecycle.clj:467)
        at cljfx.lifecycle$fn__1941$G__1934__1952.invoke(lifecycle.clj:17)
        at cljfx.renderer$render_component.invokeStatic(renderer.clj:65)
        at cljfx.renderer$render_component.invoke(renderer.clj:49)
        at cljfx.renderer$create$fn__2531.invoke(renderer.clj:79)
        at cljfx.renderer$perform_render$fn__2465.invoke(renderer.clj:23)
        at cljfx.renderer$perform_render.invokeStatic(renderer.clj:22)
        at cljfx.renderer$perform_render.invoke(renderer.clj:14)
        at cljfx.renderer$request_render$fn__2507$fn__2511.invoke(renderer.clj:46)
        at cljfx.renderer$request_render$fn__2507.invoke(renderer.clj:46)
        at clojure.lang.AFn.run(AFn.java:22)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
        at java.base/java.lang.Thread.run(Thread.java:840)
`

**Desktop (please complete the following information):**
Linux, Java 17, MegaStrike 0.2.1

**Comment by jonathanabennett** [comment]
I believe I've isolated that bug. It has to do with not having a default direction. The dev branch has a fix for that. I've made considerable progress on LOS and attacks today so I expect to have 0.3.0 out as soon as the end of this week which will address this.
